version: '2.0'
services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - es1
      - redis
    env_file: src/default.env
    ports:
      - '8080:8080'
    expose:
      - 8080
  es1:
    build: docker/elasticsearch/
    container_name: es1
    env_file: docker/elasticsearch/default.env
    volumes:
      - 'esdat1:/usr/share/elasticsearch/data'
    restart: unless-stopped
    networks:
      default:
        aliases:
          - elasticsearch
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
  redis:
    image: 'redis:4-alpine'
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  esdat1:

